# -*- coding: utf-8 -*-
"""ismart.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_bDJ6SaY8xKQE6ViUvB8eqB5nl9skco
"""

# import sys
# sys.path.append('/modules/')
# import modules
# from modules.mathy import*



# 
responses=["Welcome to smart Calculator","My name is 144p ALEXA","Sorry!This is beyond my ability"]
def extract_numbers(text):
  l=[]
  for t in text.split(" "):
    try:
      l.append(float(t))
    except ValueError:
      pass
  return (l)
def lcm(a,b):
  n=a if a>b else b
  while n<=a*b:
    if n%a==0 and n%b==0:
      return n
    n+=1
def hcf(a,b):
  n=a if a<b else b
  while n>=1:
    if a%n==0 and b%n==0:
      return n
    n-=1
def add(a,b):
  return a+b
def sub(a,b):
  return a-b
def multiply(a,b):
  return(a*b)
def divide(a,b):
  return a/b
def end():
  print(responses[2])
  input("Press Enter key to Exit") 
  exit() #predefined function to exit the program
def myname():
  print(responses[1])
def sorry():
  print(responses[2])    
operations={"PLUS":add,"ADD":add,"SUM":add,"ADDITION":add,"SUBTRACT":sub,"MINUS":sub,"MULTIPLY":multiply,"MULTIPlICATION":multiply,"DIVIDE":divide,"DIVISION":divide,"LCM":lcm,"HCF":hcf}  
commands={"NAME":myname,"END":end,"STOP":end,"EXIT":end}
# 
print(responses[0])
print(responses[1])
while True:
  print()
  text=input("Enter your problem")
  for word in text.split(" "):
     if word.upper() in operations.keys():
       try:
         l=extract_numbers(text)
         r=operations[word.upper()] (l[0],l[1])
         print(r)
       except:
         print("Something is wrong please retry")
       finally:
         break  
     elif word.upper() in commands:
       commands[word.upper()]()
       break
  else:
       sorry()